spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://0.0.0.0:3388/bilibili_cnki?useUnicode=true&character_set_server=utf8mb4
    username: root
    password: root
  cache:
    type: caffeine

  application:
    name: AsoulCnki

  redis:
    database: 0
    port: 6399
    host: 0.0.0.0
    password: 1234
    jedis:
      pool:
        max-active: 4
        max-wait: -1
        max-idle: 4
        min-idle: 0 # 最小的空闲连接数

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

logging:
  config: classpath:logback-spring.xml
  pattern:
    console: "%date [%level] [%thread] %logger{60} [%file : %line] %msg%n"
    file: "%date [%level] [%thread] %logger{60} [%file : %line] %msg%n"
  level:
    root: info
  file:
    path: logs/
    name: default.log
server:
  port: 8000
  servlet:
    context-path: /v1/api
application:
  name: AsoulCnki
  version: 1.0
  description: 枝网查重后台

secure:
  key: 123456

swagger:
  enabled: true

elasticsearch:
  ip: 0.0.0.0
  port: 9200