name: Publish Docker
on:
        push:
                branches: [master]
        pull_request:
                branches: [master]
jobs:
        build:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v2
                        - name: Set up Java8
                          uses: actions/setup-java@v2
                          with:
                                  java-version: '8'
                                  distribution: 'adopt'
                         
                        - name: Install dependencies
                          run: mvn clean install

                        - name: Cache dependencies
                          uses: actions/cache@v2
                          with:
                                path: ~/.m2/repository
                                key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                                restore-keys: |
                                        ${{ runner.os }}-maven-

                        - name: Build docker image
                          run: mvn package docker:build -DskipTests=true

                        - name: Login in docker registry
                          uses: docker/login-action@v1
                          with:
                                  username: ${{ secrets.ALI_USERNAME }}
                                  password: ${{ secrets.ALI_PASSWORD }}
                                  registry: registry.cn-hangzhou.aliyuncs.com
                                  repository: registry.cn-hangzhou.aliyuncs.com/asoulcnki/api
                                  auto_tag: true
                       
                        - name: Publish to docker registry
                          run: docker push registry.cn-hangzhou.aliyuncs.com/asoulcnki/api
